# Development-focused Docker Compose
# Use this if you only want to run dependencies, not the API
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: superapp-postgres-dev
    environment:
      POSTGRES_USER: superapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: superapp-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_dev_data:
  redis_dev_data:
