version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: superapp-postgres
    environment:
      POSTGRES_USER: superapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: superapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: superapp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superapp-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://superapp:password@postgres:5432/superapp
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
