[server]
host = "0.0.0.0"
port = 8080
workers = 4

[database]
max_connections = 100
min_connections = 5
connection_timeout = 30
idle_timeout = 600
# For Supabase, use the connection string from your Supabase dashboard
# Format: postgresql://[user]:[password]@[host]:[port]/[database]?sslmode=require

[redis]
pool_size = 10
connection_timeout = 5

[security]
token_expiry = 3600
refresh_token_expiry = 2592000  # 30 days
password_min_length = 8
max_login_attempts = 5
lockout_duration = 900  # 15 minutes

[blockchain]
network = "devnet"
commitment = "confirmed"
transaction_timeout = 60

[ai]
inference_threads = 4
batch_size = 32
cache_ttl = 3600

[rate_limiting]
requests_per_minute = 100
burst_size = 20

[cors]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
allowed_headers = ["Authorization", "Content-Type"]
max_age = 3600

[logging]
level = "info"
format = "json"

[metrics]
enabled = true
port = 9090
